# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9611943e14d0124b4cb30f79625d0e8f3a692bd635d664511186f100f05446865144541c3d3c936054ebad4c77d5d9a362d0195fcc3cffa787e12ed315c25520

test:
  secret_key_base: 82174a44a8fad6cb5473254a0ac91b7eba8cac523288368dc747b97634acce77916ac02339b353650c0b8311de89865ec5a9e7da77b2bc73361613f42d247c64

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
